/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Service2;


public enum Error implements org.apache.thrift.TEnum {
  DEVIDE_BY_ZERO(1),
  OVERFLOW(2),
  UNKNOWN(3);

  private final int value;

  private Error(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Error findByValue(int value) { 
    switch (value) {
      case 1:
        return DEVIDE_BY_ZERO;
      case 2:
        return OVERFLOW;
      case 3:
        return UNKNOWN;
      default:
        return null;
    }
  }
}
