/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package k3v1n1k88.TestLogScribe;


public enum Item implements org.apache.thrift.TEnum {
  BUA(1),
  DAO(2),
  SUNG(3),
  GAY(4);

  private final int value;

  private Item(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Item findByValue(int value) { 
    switch (value) {
      case 1:
        return BUA;
      case 2:
        return DAO;
      case 3:
        return SUNG;
      case 4:
        return GAY;
      default:
        return null;
    }
  }
}
